# forge "http://forge.puppetlabs.com"

# mod "puppetlabsapt", "1.4.0"

# forge "https://forgeapi.puppetlabs.com"

# mod 'puppetlabs-apt',
#   :git => "git://github.com/puppetlabs/puppetlabs-apt.git",
#   :ref => '1.4.0'